# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - klustr-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.AzureAppService_ContainerUsername_6bb09d0db64b47988f22cdd78ea43c67 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_ff16293c5913433e93093b08690ac7bf }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'klustr-api'
            slot-name: 'production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_2c72d999570046e2b422d424b657ed15 }}
            images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6bb09d0db64b47988f22cdd78ea43c67 }}/v1/rushi0508/klustr-api:${{ github.sha }}'
